# Generated by Django 5.2 on 2025-05-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=35)),
                ('mob_no', models.CharField(max_length=12)),
                ('user_image', models.FileField(default=None, max_length=250, null=True, upload_to='user/')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
