# Generated by Django 5.2 on 2025-05-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0002_webusers_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='email',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='mob_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
