# Generated by Django 5.2 on 2025-05-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0004_alter_webusers_email_alter_webusers_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webusers',
            old_name='email',
            new_name='email_id',
        ),
    ]
