# Generated by Django 5.2 on 2025-05-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0005_rename_email_webusers_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webusers',
            name='email_id',
        ),
    ]
