# Generated by Django 5.2 on 2025-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0006_remove_webusers_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webusers',
            name='email_id',
            field=models.EmailField(default=None, max_length=35, unique=True),
        ),
    ]
