# Generated by Django 5.2 on 2025-05-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0007_webusers_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='email_id',
            field=models.EmailField(blank=True, default=None, max_length=35),
        ),
    ]
