# Generated by Django 5.2 on 2025-05-11 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0008_alter_webusers_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webusers',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
