# Generated by Django 5.2 on 2025-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0009_webusers_date_joined_webusers_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='mob_no',
            field=models.CharField(blank=True, default='/user/default-profile-picture-grey-mal.png', max_length=12, null=True),
        ),
    ]
