# Generated by Django 5.2 on 2025-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0010_alter_webusers_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='mob_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='user_image',
            field=models.FileField(default='/user/default-profile-picture-grey-mal.png', max_length=250, null=True, upload_to='user/'),
        ),
    ]
