# Generated by Django 5.2 on 2025-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('food', models.CharField(max_length=70)),
                ('Price', models.IntegerField()),
                ('Quantity', models.PositiveIntegerField(default=1, null=True)),
                ('Special_Instructions', models.TextField(default=None, null=True)),
                ('order_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='delivery', max_length=20)),
                ('payment_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
