# Generated by Django 5.2 on 2025-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orderedfood', '0003_alter_order_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Price',
            field=models.CharField(),
        ),
    ]
