# Generated by Django 5.2 on 2025-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orderedfood', '0005_alter_order_food_alter_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
