# Generated by Django 5.2 on 2025-04-23 09:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
