# Generated by Django 5.2 on 2025-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_service_slug_service_menu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='food/'),
        ),
    ]
