# Generated by Django 5.2 on 2025-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(default='\\static\\img\\set-vector.jpg', max_length=250, null=True, upload_to='food/'),
        ),
    ]
