# Generated by Django 5.2 on 2025-04-24 05:26

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_service_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainpage_image', models.FileField(default='/food/set-vector.jpg', max_length=250, null=True, upload_to='food/')),
                ('mainpage_title', models.CharField(max_length=50)),
                ('mainpage_desc', tinymce.models.HTMLField()),
                ('mainpage_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True)),
            ],
        ),
    ]
