# Generated by Django 5.2 on 2025-04-24 05:44

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='mainpage_image',
            field=models.FileField(default='/mainpage/set-vector.jpg', max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='mainpage_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='mainpage_title', unique=True),
        ),
    ]
