# Generated by Django 5.2 on 2025-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_mainpage_mainpage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='mainpage_image',
            field=models.FileField(default='/mainpage/set-vector.jpg', max_length=250, null=True, upload_to='mainpage/'),
        ),
    ]
