# Generated by Django 5.2 on 2025-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_mainpage_mainpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_badge',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_deal',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_emi',
            field=models.IntegerField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_oldprice',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_rating',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
