# Generated by Django 5.2 on 2025-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_service_service_badge_service_service_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_emi',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_badge',
            field=models.CharField(blank=True, default="Amazon's Choice", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_deal',
            field=models.IntegerField(blank=True, default=20, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_oldprice',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_rating',
            field=models.CharField(blank=True, default=100, max_length=20, null=True),
        ),
    ]
