# Generated by Django 5.2 on 2025-04-24 07:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_service_service_emi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
