# Generated by Django 5.2 on 2025-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_service_service_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_deal',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_oldprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, max_length=10, null=True),
        ),
    ]
