# Generated by Django 5.2 on 2025-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_service_service_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_oldprice',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.IntegerField(default=None, max_length=10, null=True),
        ),
    ]
