# Generated by Django 5.2 on 2025-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_remove_cart_item_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_image',
            field=models.FileField(default='/food/set-vector.jpg', max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_rating',
            field=models.CharField(blank=True, default=100, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
