# Generated by Django 5.2 on 2025-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_remove_cart_items_cart_item_image_cart_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='food/'),
        ),
    ]
