# Generated by Django 5.2 on 2025-04-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_cart_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
