# Generated by Django 5.2 on 2025-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_cart_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
