# Generated by Django 5.2 on 2025-04-30 15:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_cart_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
    ]
