# Generated by Django 5.2 on 2025-05-10 14:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_cart_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_rating',
            field=models.CharField(blank=True, default='100', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='item_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_rating',
            field=models.CharField(blank=True, default='100', max_length=20, null=True),
        ),
    ]
