# Generated by Django 5.2 on 2025-05-20 11:52

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0009_webusers_date_joined_webusers_last_login'),
        ('service', '0026_service_discount_alter_cart_item_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_rating',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_slug',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_title',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='SysAdmin.webusers'),
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('item_price', models.IntegerField(default=None, null=True)),
                ('item_rating', models.CharField(blank=True, default='100', max_length=20, null=True)),
                ('item_image', models.FileField(default=None, max_length=250, null=True, upload_to='food/')),
                ('item_quantity', models.PositiveIntegerField(default=1, null=True)),
                ('item_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='item_title', unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.cart')),
            ],
        ),
    ]
