# Generated by Django 5.2 on 2025-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
