# Generated by Django 5.2 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_alter_cart_created_at_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
