# Generated by Django 5.2 on 2025-05-20 12:14

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0009_webusers_date_joined_webusers_last_login'),
        ('service', '0036_alter_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_rating',
            field=models.CharField(blank=True, default='100', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='item_title', unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='SysAdmin.webusers'),
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
