# Generated by Django 5.2 on 2025-05-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
