# Generated by Django 5.2 on 2025-05-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0011_alter_webusers_mob_no_alter_webusers_user_image'),
        ('service', '0041_remove_cart_created_at_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='SysAdmin.webusers'),
        ),
    ]
