# Generated by Django 5.2 on 2025-05-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0043_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
