# Generated by Django 5.2 on 2025-05-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='cart_user',
        ),
    ]
