# Generated by Django 5.2 on 2025-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0045_rename_user_id_cart_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_image',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
