# Generated by Django 5.2 on 2025-05-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_alter_cart_item_image_alter_cart_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_rating',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_title',
        ),
    ]
