# Generated by Django 5.2 on 2025-05-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0011_alter_webusers_mob_no_alter_webusers_user_image'),
        ('service', '0047_remove_cart_cart_user_remove_cart_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='SysAdmin.webusers'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_rating',
            field=models.CharField(blank=True, default='100', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
