# Generated by Django 5.2 on 2025-05-30 12:00

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysAdmin', '0011_alter_webusers_mob_no_alter_webusers_user_image'),
        ('service', '0048_cart_cart_user_cart_item_image_cart_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='SysAdmin.webusers'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_image',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='food/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='item_title', unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='mainpage_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='mainpage_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='menu_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='service_title', unique=True),
        ),
    ]
