# Generated by Django 5.2 on 2025-05-11 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquery',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
